ci: check `name` validity
siyuan-note/bazaar pull request #1115
Opened 2023-05-12 04:20 UTC by Zuoqiu-Yingyi

检查清单文件中 `name` 字段的有效性

- 大小写不敏感
- 检查是否均为可打印的 ASCII 字符
- 检查是否包含无效字符
  - `\`
  - `/`
  - `:`
  - `*`
  - `?`
  - `"`
  - `<`
  - `>`
  - `|`
- 检查是否以 `.` 或者 ` ` 开头或者结尾
- 检查是否为保留字
  - `CON`
  - `PRN`
  - `AUX`
  - `NUL`
  - `COM0`
  - `COM1`
  - `COM2`
  - `COM3`
  - `COM4`
  - `COM5`
  - `COM6`
  - `COM7`
  - `COM8`
  - `COM9`
  - `LPT0`
  - `LPT1`
  - `LPT2`
  - `LPT3`
  - `LPT4`
  - `LPT5`
  - `LPT6`
  - `LPT7`
  - `LPT8`
  - `LPT9`

2023-05-12 07:06 UTC, 88250 requested changes

2023-05-12 07:06 UTC, 88250 commented on actions/check/main.go
> +	// go checkRepos(PR_REPO_PATH+"/icons.json", "./stage/icons.json", icons, check_result, wait_group)
这里注释掉的原因是？

2023-05-12 07:06 UTC, 88250 commented on actions/check/main.go
>  		origin_url := origin_repo.(map[string]interface{})["url"].(string)
变量建议用驼峰命名。

2023-05-12 07:36 UTC, Zuoqiu-Yingyi commented on actions/check/main.go
> +	// go checkRepos(PR_REPO_PATH+"/icons.json", "./stage/icons.json", icons, check_result, wait_group)
测试完成忘了恢复了😂

2023-05-12 07:38 UTC, Zuoqiu-Yingyi commented on actions/check/main.go
>  		origin_url := origin_repo.(map[string]interface{})["url"].(string)
临时变量使用蛇形命名用于与参数/返回值区分

2023-05-12 07:48 UTC, 88250 commented on actions/check/main.go
>  		origin_url := origin_repo.(map[string]interface{})["url"].(string)
按照统一的命名规范来吧，目前程序中统一使用驼峰命名。

如果要强调返回值可以加前缀 `ret`，比如 `retXxx`。

2023-05-12 07:50 UTC, Zuoqiu-Yingyi commented on actions/check/main.go
>  		origin_url := origin_repo.(map[string]interface{})["url"].(string)
那我晚些时候改改后重新申请审阅

2023-05-13 09:44 UTC, 88250 approved these changes

2023-05-13 09:44 UTC, merged