之前提交的主题  合并时少了一个白天模式ReedLight
siyuan-note/bazaar pull request #71
Opened 2021-02-23 11:40 UTC by reedtop

2021-02-23 12:03 UTC, 88250 commented
1. 预览图请使用横屏截图
2. 预览图请更新格式为 png
3. 请解决冲突

2021-02-23 13:40 UTC, 88250 requested changes

2021-02-23 13:40 UTC, 88250 commented on themes.json
> +    "reedtop/ReedDark@648615a86bf38355c22b1c3cbe1bac337a37f31c",
你好，请重新修改这两款主题：

* 预览图请使用横屏截图
* 预览图请更新格式为 png

2021-02-24 00:40 UTC, reedtop commented
已经更新图片  麻烦了

2021-02-24 02:17 UTC, merged