更新至0.1.8 增加批量制卡，sm材料卡，导出opml的功能
siyuan-note/bazaar pull request #781
Opened 2022-07-19 14:38 UTC by TheGodOfKing

![](https://notetocard.oss-cn-hangzhou.aliyuncs.com/4D68F927D4E2B1D1BFDA8B5402A70333.png)

2022-07-19 14:56 UTC, 88250 requested changes
这个 commit hash 并不存在，请确认一下。

![image](https://user-images.githubusercontent.com/873584/179781766-758bdfa9-5408-49b2-a473-c8079e5236ad.png)

另外，请注意保持 widgets.json 的 JSON 格式有效（目前缺失 `,`）

2022-07-19 15:24 UTC, 88250 commented
`9b14fa4468002cecba22120a00850d266ddef495` 不存在哦

![image](https://user-images.githubusercontent.com/873584/179788269-c04b2e4a-f912-4e1c-b438-0b90f7170454.png)

2022-07-19 15:24 UTC, 88250 commented
另外，请解决冲突。

2022-07-19 15:38 UTC, TheGodOfKing commented
大师我悟了，这下应该没问题了

2022-07-19 15:39 UTC, 88250 commented
https://github.com/siyuan-note/bazaar/pull/782

2022-07-19 15:39 UTC, closed without merging

2022-07-23 12:51 UTC, tcmtom commented
怎么集市里面找不到了